server:
  port: 13682
  servlet:
    context-path: /
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.32.12:3306/tmapp_base?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: TMKJdzgj@2020
    username: root
    password: 6000
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      #connection-test-query: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            # 默认
            instanceName: DemoScheduler
            # 如果使用集群，instanceId必须唯一，设置成AUTO
            instanceId: AUTO
          jobStore:
            # 存储方式使用JobStoreTX 也就是数据库
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表名前缀
            tablePrefix: QRTZ_
            # 是否使用集群
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            misfireThreshold: 5000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    jdbc:
      # 启动项目时是否初始化表
      initialize-schema: never
#打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config: 123
